packaging_format = 2

id = "librey"
name = "LibreY"
description.en = "Self-hosted meta-search engine without JavaScript, fork of LibreX"
description.fr = "Moteur de métarecherche auto-hébergé sans JavaScript, fork de LibreX"
version = "1.0~ynh1"
maintainers = ["ton_pseudo"]

[upstream]
license = "AGPL-3.0"
website = "https://github.com/Ahwxorg/LibreY"
admindoc = "https://github.com/Ahwxorg/LibreY"
userdoc = "https://github.com/Ahwxorg/LibreY"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]

[install]
    [install.domain]
    type = "domain"
    help = "Choisissez le sous-domaine où LibreY sera installé (ex: librey.mondomaine.tld)."
    default = "librey.example.tld"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://github.com/Ahwxorg/LibreY/archive/refs/heads/main.tar.gz"
    sha256 = "" # à compléter après test
    autoupdate.strategy = "latest_commit"

    [resources.apt]
    packages = ["nginx"]

    [resources.system_user]
    name = "librey"

    [resources.permissions]
    main.url = "/"
